{{- include "redis.validateAuth" . -}}

{{- if eq .Values.architecture "replication" }}
apiVersion: {{ include "common.capabilities.statefulset.apiVersion" . }}
kind: StatefulSet
metadata:
  name: {{ include "common.names.fullname" . }}-master
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: redis
    redis.io/role: master
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  serviceName: {{ include "common.names.fullname" . }}-headless-master
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
      redis.io/role: master
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: redis
        redis.io/role: master
        {{- if .Values.redis.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.redis.podLabels "context" $) | nindent 8 }}
        {{- end }}
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap-configuration.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- if .Values.redis.podAnnotations }}
        {{- include "common.tplvalues.render" (dict "value" .Values.redis.podAnnotations "context" $) | nindent 8 }}
        {{- end }}
        {{- if .Values.commonAnnotations }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.redis.podSecurityContext.enabled }}
      securityContext: {{- include "common.security.podSecurityContext" (dict "securityContext" .Values.redis.podSecurityContext "context" .) | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "redis.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.redis.serviceAccount.automountServiceAccountToken }}
      enableServiceLinks: false
      {{- if .Values.master.schedulerName }}
      schedulerName: {{ .Values.master.schedulerName | quote }}
      {{- end }}
      {{- if .Values.master.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" ( dict "value" .Values.master.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.master.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.master.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.master.topologySpreadConstraints }}
      topologySpreadConstraints: {{- include "common.tplvalues.render" (dict "value" .Values.master.topologySpreadConstraints "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.master.affinity }}
      affinity: {{- include "common.tplvalues.render" ( dict "value" .Values.master.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        {{- if .Values.master.podAffinityPreset }}
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.master.podAffinityPreset "component" "master" "context" $) | nindent 10 }}
        {{- end }}
        {{- if .Values.master.podAntiAffinityPreset }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.master.podAntiAffinityPreset "component" "master" "context" $) | nindent 10 }}
        {{- end }}
        {{- if .Values.master.nodeAffinityPreset.type }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.master.nodeAffinityPreset.type "key" .Values.master.nodeAffinityPreset.key "values" .Values.master.nodeAffinityPreset.values) | nindent 10 }}
        {{- end }}
      {{- end }}
      {{- if .Values.master.initContainers }}
      initContainers: {{- include "common.tplvalues.render" (dict "value" .Values.master.initContainers "context" $) | nindent 8 }}
      {{- end }}
      containers:
        - name: redis
          image: {{ include "common.images.image" (dict "imageRoot" .Values.image "global" .Values.global) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.redis.containerSecurityContext.enabled }}
          securityContext: {{- include "common.security.containerSecurityContext" (dict "securityContext" .Values.redis.containerSecurityContext "context" .) | nindent 12 }}
          {{- end }}
          command:
            - /opt/redis-config/startup-master.sh
          env:
            - name: REDIS_REPLICATION_MODE
              value: master
            {{- if .Values.auth.enabled }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "redis.secretName" . }}
                  key: {{ include "redis.secretPasswordKey" . }}
            {{- end }}
          ports:
            - name: redis
              containerPort: {{ .Values.master.containerPorts.redis }}
              protocol: TCP
          {{- if .Values.redis.livenessProbe.enabled }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.redis.livenessProbe "enabled") "context" $) | nindent 12 }}
            exec:
              command:
                - sh
                - -c
                {{- if .Values.auth.enabled }}
                - redis-cli -h localhost -p {{ .Values.master.containerPorts.redis }} -a $REDIS_PASSWORD ping
                {{- else }}
                - redis-cli -h localhost -p {{ .Values.master.containerPorts.redis }} ping
                {{- end }}
          {{- end }}
          {{- if .Values.redis.readinessProbe.enabled }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.redis.readinessProbe "enabled") "context" $) | nindent 12 }}
            exec:
              command:
                - sh
                - -c
                {{- if .Values.auth.enabled }}
                - redis-cli -h localhost -p {{ .Values.master.containerPorts.redis }} -a $REDIS_PASSWORD ping
                {{- else }}
                - redis-cli -h localhost -p {{ .Values.master.containerPorts.redis }} ping
                {{- end }}
          {{- end }}
          {{- if .Values.redis.startupProbe.enabled }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.redis.startupProbe "enabled") "context" $) | nindent 12 }}
            exec:
              command:
                - sh
                - -c
                {{- if .Values.auth.enabled }}
                - redis-cli -h localhost -p {{ .Values.master.containerPorts.redis }} -a $REDIS_PASSWORD ping
                {{- else }}
                - redis-cli -h localhost -p {{ .Values.master.containerPorts.redis }} ping
                {{- end }}
          {{- end }}
          {{- if ne .Values.master.resourcesPreset "none" }}
          resources: {{- include "common.resources.preset" (dict "type" .Values.master.resourcesPreset) | nindent 12 }}
          {{- else if and .Values.master.resources.limits.memory .Values.master.resources.limits.cpu }}
          resources: {{- toYaml .Values.master.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.master.lifecycleHooks }}
          lifecycle: {{- include "common.tplvalues.render" (dict "value" .Values.master.lifecycleHooks "context" $) | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: redis-config
              mountPath: /opt/redis-config
            - name: redis-data
              mountPath: /data
            # Required writable directories for read-only root filesystem
            - name: redis-tmp-conf
              mountPath: /tmp
            {{- if .Values.master.extraVolumeMounts }}
            {{- include "common.tplvalues.render" (dict "value" .Values.master.extraVolumeMounts "context" $) | nindent 12 }}
            {{- end }}
        {{- if .Values.master.sidecars }}
        {{- include "common.tplvalues.render" (dict "value" .Values.master.sidecars "context" $) | nindent 8 }}
        {{- end }}
      volumes:
        - name: redis-config
          configMap:
            name: {{ include "common.names.fullname" . }}-configuration
            defaultMode: 0755
        # Writable directories for read-only root filesystem
        - name: redis-tmp-conf
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
        {{- if .Values.master.extraVolumes }}
        {{- include "common.tplvalues.render" (dict "value" .Values.master.extraVolumes "context" $) | nindent 8 }}
        {{- end }}
        {{- if .Values.master.persistence.existingClaim }}
        - name: redis-data
          persistentVolumeClaim:
            claimName: {{ .Values.master.persistence.existingClaim }}
        {{- else if not .Values.master.persistence.enabled }}
        - name: redis-data
          emptyDir: {}
        {{- end }}
  {{- if and .Values.master.persistence.enabled (not .Values.master.persistence.existingClaim) }}
  volumeClaimTemplates:
    - metadata:
        name: redis-data
        {{- if .Values.master.persistence.annotations }}
        annotations: {{- include "common.tplvalues.render" (dict "value" .Values.master.persistence.annotations "context" $) | nindent 10 }}
        {{- end }}
      spec:
        accessModes:
        {{- range .Values.master.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.master.persistence.size | quote }}
        {{- if .Values.master.persistence.selector }}
        selector: {{- include "common.tplvalues.render" (dict "value" .Values.master.persistence.selector "context" $) | nindent 10 }}
        {{- end }}
        {{- if .Values.master.persistence.storageClass }}
        {{- if (eq "-" .Values.master.persistence.storageClass) }}
        storageClassName: ""
        {{- else }}
        storageClassName: {{ .Values.master.persistence.storageClass | quote }}
        {{- end }}
        {{- else if .Values.global.storageClass }}
        {{- if (eq "-" .Values.global.storageClass) }}
        storageClassName: ""
        {{- else }}
        storageClassName: {{ .Values.global.storageClass | quote }}
        {{- end }}
        {{- end }}
  {{- end }}
{{- end }}
