{{- include "redis-cluster.validateAuth" . -}}
{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: redis-cluster
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.auth.password }}
  redis-password: {{ .Values.auth.password | b64enc | quote }}
  {{- else }}
  redis-password: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
{{- end }}
